name: CI devops 2024
on:
  push:
    branches:
      - main
      - develop
  pull_request:
jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout code from the repository
      - uses: actions/checkout@v2.5.0

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Build and test the project with Maven
      - name: Build and test with Maven
        working-directory: ./simple-api # 确保这里是包含 pom.xml 的目录
        run: mvn clean verify

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      # Checkout code from the repository
      - uses: actions/checkout@v2.5.0

      # Login to DockerHub
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image for backend
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}
